# Generated by Django 4.2.3 on 2024-04-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'article_category',
            },
        ),
        migrations.CreateModel(
            name='CategoryGroupRank',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('rank', models.JSONField(max_length=50000, null=True)),
            ],
            options={
                'db_table': 'article_category_group_rank',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'article_tag',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=500)),
                ('description', models.TextField(default='', max_length=5000)),
                ('content', models.TextField(default='', max_length=50000)),
                ('cover_img', models.CharField(default='', max_length=200)),
                ('rank', models.PositiveIntegerField(default=99999)),
                ('categories', models.ManyToManyField(db_constraint=False, related_name='articles', to='article.category')),
                ('tags', models.ManyToManyField(db_constraint=False, related_name='articles', to='article.tag')),
            ],
            options={
                'db_table': 'article_article',
            },
        ),
    ]
