# Generated by Django 4.2.3 on 2024-04-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_slug_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAdInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('terms', models.CharField(default='', max_length=1000)),
                ('terms_style_id', models.CharField(default='', max_length=50)),
                ('results_style_id', models.CharField(default='', max_length=50)),
                ('channel_id', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'article_search_ad_info',
            },
        ),
    ]
