# Generated by Django 4.2.3 on 2024-05-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_searchadinfo_results_style_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='referrer_ad_creative',
            field=models.CharField(default='', max_length=250),
        ),
    ]
